app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /

TaskController:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /api

api_login_check:
    path: /api/login